raw_user_data_path: data/raw_data/user_data.csv
raw_post_data_path: data/raw_data/post_data.csv
raw_feed_data_path: data/raw_data/feed_data.csv

processed_user_data_path: data/processed_data/user_data.csv
processed_post_data_path: data/processed_data/post_data.csv
processed_result_data_path: data/processed_data/result_data.csv